fixed backups

diff --git a/cleanup b/cleanup
--- a/cleanup
+++ b/cleanup
@@ -5,6 +5,14 @@ cd /mnt/e/ToC/src
 rm *.o
 rm merc
 make
+if [ $? -eq 0 ]
+then
+  echo "ToC Successfully Compiled"
+else
+  echo "Could not compile." >&2 
+  exit
+fi
+
 rm *.o
 rm ../area/merc
 cp merc ../area
@@ -13,15 +21,15 @@ cd ..
 set +x
 echo "Done."
 echo ""
-sleep 3
-
+sleep 1
 cd /mnt/e/ToC/
 
 read -p "Kill any existing sessions and then reload ToC? [y/n?] "  RESPONSE
 if [ "$RESPONSE" = y ]; then
 (pkill -e merc; pkill -e immortal; pkill -e startup; ./startup &) &
 elif [ "$RESPONSE" = n ]; then
-	echo "Reboot in game for changes to take effect."
+	echo ""
+	echo "Game not reloaded.  Reboot in game for changes to take effect."
 else
 	echo "Make a valid selection! [y or n]"
 fi
